### ISSUE TITLE
Peer to Peer Morning session

### ISSUE THREAD

**Issue by jkanyi-web** [MussieTeka/Leaderboard#5]
Hi Mussie, very good code presentation and functionality. Very neat and presentable.
However, I think the html code would look even more presentable and modern if you use semantic html tags like <section></section>, <header></header>, etc., in place of the div tags you used.

**Comment by MussieTeka** [comment]
Hi @jkanyi-web,

Thank you for your constructive feedback and I will consider your comment on my future assignments.

Best,
Mussie
